### PR TITLE
Update SlamData.md

### PR DESCRIPTION
**Pull request by JeffACarr**
Added commercial support option

### CODE REVIEW

**Comment by stennie** [comment]
@JeffACarr Thanks for the PR, however we're not using/displaying the "support" attribute at the moment. Originally this was used to indicate whether a tool was officially supported by MongoDB, but we should update to something clearer like a support url or email address.

**Comment by IanWhalen** [comment]
we should also just do a find-and-replace to make "support" something like "mongodb-inc-support"?

**Comment by JeffACarr** [comment]
Stennie and Ian, thanks for clarifying the point, was misreading it.

**Comment by stennie** [comment]
@JeffACarr Not a problem .. it was definitely unclear. We're working on improving the information and formatting, so any suggestions appreciated. I added issue #55 to clean up the "support" attribute.

**Comment by JeffACarr** [comment]
Maybe have two columns, "MongoDB supported" (Yes/No) and "Vendor Support" (Yes/No).  Adds a column so a bit messier, but provides for maximum flexibility

**Pull request closed without merging**
