### PR TITLE
Create Countly.md

### PR DESCRIPTION
**Pull request by gorkem-cetin**

### CODE REVIEW

**Comment by stennie** [comment]
@gorkem-cetin Looks like you forgot to add `img/countly.png` to the PR?

**Comment by gorkem-cetin** [comment]
Yes, had an issue with my terminal and then totally forgot. You should receive the pull request.

**Comment by IanWhalen** [comment]
Hey @gorkem-cetin - just wanted to give you a heads up that I'm inclined to revert this particular addition.  I've checked it out and Countly definitely looks like a great platform, but I'm uncertain that it fits into the broader goal that I have for this particular site.

That goal (roughly speaking) is to help people who are already using MongoDB or considering using it to do so more easily.  From what I can tell Countly is instead a site that just uses MongoDB.  Seem accurate?  Let me know if that seems like I'm misunderstanding your platform at all.

**Comment by gorkem-cetin** [comment]
Hey Ian, while our web page doesn't run on MongoDB, the software that we provide on Github is. Countly software is open source and uses MongoDB as a backend. So please do not take the "web page" into consideration, but the software that Countly team develops on Github (http://github.com/countly/countly-server)

**Comment by gorkem-cetin** [comment]
Kind reminder & ping to reevaluate :)

**Comment by IanWhalen** [comment]
Hey Gorkem, to clarify: the idea here isn't to link to software that uses MongoDB as a backend, it's to link to software that makes life easier for those using MongoDB.  As such, I do still think that this isn't the perfect fit for this directory.

**Comment by gorkem-cetin** [comment]
Makes complete sense :-)

**Pull request merged**
