### PR TITLE
Add Python-Eve REST APIs for Humans

### PR DESCRIPTION
**Pull request by nicolaiarocci**

### CODE REVIEW

**Comment by nicolaiarocci** [comment]
Cleaning up the mess... sorry about that.

**Comment by stennie** [comment]
@nicolaiarocci looks like you need a few minor tweaks:
```
img: eve_logo.png 
permalink: /tool/eve/
```

**Comment by stennie** [comment]
@nicolaiarocci One more tweak: can you also resize the logo down to 370 x 200px? Thanks :)

**Comment by nicolaiarocci** [comment]
Should be all fixed now.

**Pull request closed without merging**
